package pl.gddkia.roadgis.domain;

public enum DraftStatus {
  NIE_DOTYCZY,
  DODANY_DO_WERSJI_ROBOCZEJ,
  W_MODYFIKACJI,
  ZAPISANY_W_WERSJI_ROBOCZEJ,
  ZAPISANY_I_DALEJ_MODYFIKOWANY,
  GOTOWY_DO_WALIDACJI,
  GOTOWY_DO_ZAPISU_FINALNEGO,
  ZAPISANY_DO_BAZY_FINALNEJ,
  ODRZUCONY
}
