package pl.gddkia.roadgis.domain;

public enum ValidationStatus {
  OK,
  BRAK_DOWIAZANIA_DO_SR,
  NIEPOPRAWNE_DANE_ATRYBUTOWE,
  NIEPOPRAWNA_GEOMETRIA,
  KONFLIKT_TOPOLOGICZNY,
  BRAK_WYMAGANYCH_ATRYBUTOW,
  POZA_ZAKRESEM_UPRAWNIEN,
  WYMAGA_WERYFIKACJI_OPERATORA,
  OSTRZEZENIE
}
